package up

const (
	OPENAPIURL = "https://qra.95516.com/pay/gateway"
)

const (
	MESSAGE_PAYING   = "MESSAGE_PAYING"
	MESSAGE_UNIONPAY = "MESSAGE_UNIONPAY"
	MESSAGE_OVERTIME = "MESSAGE_OVERTIME"
)

const (
	PRE_OUTTRADENO    = "20"
	PRE_OUTREFUNDNO   = "21"
	PRE_PREOUTTRADENO = "22"
)
