package up

const (
	OPENAPIURL = "https://qra.95516.com/pay/gateway"
)

const (
	SYSTEMERROR   = "SYSTEMERROR"
	ORDERNOTEXIST = "ORDERNOTEXIST"
	BANKERROR     = "BANKERROR"
	USERPAYING    = "USERPAYING"
)

const (
	MESSAGE_PAYING   = "MESSAGE_PAYING"
	MESSAGE_UNIONPAY = "MESSAGE_UNIONPAY"
	MESSAGE_OVERTIME = "MESSAGE_OVERTIME"
)

const (
	PAY_OVERTIME           = 60 //default 60s
	PAY_LOOPQUERY_INTERVAL = 2
)

const (
	PRE_OUTTRADENO    = "20"
	PRE_OUTREFUNDNO   = "21"
	PRE_PREOUTTRADENO = "22"
)
